[workspace]
members = ["./crates/*", "crates/shared"]
resolver = "2"

[profile.release]
debug = true

[workspace.dependencies]
axum = { version = "0.7", features = ["ws"] }
axum-extra = { version = "0.9", features = ["cookie"] }
tower-http = { version = "0.6", features = ["trace"] }
fxhash = "0.2"

tokio = { version = "1", features = ["full", "tracing"] }
tungstenite = "0.24"
tokio-tungstenite = "0.24"
futures = "0.3"

sqlx = { version = "0.8", default-features = false, features = [
    "runtime-tokio-rustls",
    "mysql",
    "macros",
    "chrono",
    "rust_decimal",
] }
reqwest = { version = "0.12", default-features = false, features = [
    "rustls-tls",
    "http2",
    "json",
] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"

ulid = "1"
chrono = { version = "0.4", features = ["serde"] }
thiserror = "2"

shared = { path = "./crates/shared" }
