[workspace]
members = ["./crates/*", "crates/shared"]
resolver = "2"

[profile.release]
debug = true

[workspace.dependencies]
axum = "0.7"
tower-http = { version = "0.6", features = ["trace"] }
fxhash = "0.2"

tokio = { version = "1", features = ["full", "tracing"] }
tokio-tungstenite = "0.26.0"
futures = "0.3"

sqlx = { version = "0.8", default-features = false, features = [
    "runtime-tokio-rustls",
    "mysql",
    "macros",
    "chrono",
    "rust_decimal",
] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"

ulid = "1"
chrono = "0.4"

shared = { path = "./crates/shared" }
