services:
  db:
    image: mysql
    container_name: isuride-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: isucon
      MYSQL_DATABASE: isuride
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "2"
    # volumes:
    #   - ./mysql_logs:/var/log/mysql
    # command:
    #   [
    #     "--log-error=/var/log/mysql/error.log",
    #     "--general-log=1",
    #     "--general-log-file=/var/log/mysql/general.log",
    #   ]
    ports:
      - "3306:3306"

  nginx:
    image: nginx:latest
    network_mode: host
    container_name: isuride-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ulimits:
      nofile:
        soft: "655360"
        hard: "655360"
