[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
fxhash = { workspace = true }
tokio = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
derivative = "2"
